language: android
jdk: oraclejdk8
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    
     # The BuildTools version used by your project
    - build-tools-26.0.2
    
     # Extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # The SDK version used to compile your project
    - android-26

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'
