language: android
jdk: oraclejdk8
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    
     # The BuildTools version used by your project
    - build-tools-27
    
     # Extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # The SDK version used to compile your project
    - android-27

  licenses:
    - '.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
