language: android
jdk: oraclejdk8
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    
     # The BuildTools version used by your project
    - build-tools-27
    
     # Extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # The SDK version used to compile your project
    - android-27

  licenses:
    - '.+'
    
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
