sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    
     # The BuildTools version used by your project
    - build-tools-27
    
     # Extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # The SDK version used to compile your project
    - android-27

  licenses:
    - '.+'

script: ./gradlew clean test
before_script:
  - chmod +x gradlew
